nginx: add handler to restart nginx when configuration changes
jboss-set/zeus pull request #101
Opened 2021-09-14 12:31 UTC by TomasHofman

@rpelisse @spyrkob am I correct that this should cause nginx to be restarted when some tasks cause modifications?

2021-09-14 12:37 UTC, spyrkob commented
I think you need add 
```
notify:
    - Restart nginx
```
on tasks that require restart

2021-09-14 12:39 UTC, rpelisse commented
@TomasHofman Yes, that is how it's working. It funny, I really thought I came around adding this handler...

2021-09-14 12:59 UTC, TomasHofman commented
OK, I added some notifies here and there, but I'm not sure if it's working. `ansible-playbook --syntax-check zeus.yml` doesn't seem to check the nested roles, or at least I'm not able to break it. I will need to investigate more on testability later....

2021-09-23 08:28 UTC, spyrkob approved these changes

2021-09-24 07:39 UTC, spyrkob requested changes

2021-09-24 07:39 UTC, spyrkob commented on roles/nginx/tasks/http_cache_setup.yml
> +  notifies:
@TomasHofman that should be `notify`, sorry missed it earlier

2021-09-24 07:39 UTC, spyrkob commented on roles/nginx/tasks/nginx_config.yml
> +      notifies:
same as above

2021-09-24 07:39 UTC, spyrkob commented on roles/nginx/tasks/ssl.yml
> +  notifies:
same as above

2021-09-24 07:48 UTC, TomasHofman commented on roles/nginx/tasks/http_cache_setup.yml
> +  notifies:
Sorry, PR updated :)

2021-09-24 07:55 UTC, spyrkob commented
thanks :)

2021-09-24 07:55 UTC, merged