jobs: Adding JDKs 6, 7 and IBM JDK 8
jboss-set/zeus pull request #107
Opened 2021-10-04 16:39 UTC by TomasHofman

2021-10-05 07:13 UTC, spyrkob requested changes

2021-10-05 07:13 UTC, spyrkob commented on roles/java/tasks/main.yml
> +- include_tasks: tasks/java_tools_setup.yml
`tool_install` sets up `home_folder` that is used by `java_tools_setup`, I'm not sure if calling setup first will work correctly

2021-10-05 07:13 UTC, spyrkob commented on roles/java/tasks/main.yml
> +- include_tasks: tasks/tool_install.yml
If `java_tool_setup` is pulled out of `tool_install`, I think it makes more sense to change the `tool_install` to only create symlink (or even inline that in `main`) and call it in a loop rather then one by one

2021-10-05 08:42 UTC, TomasHofman commented on roles/java/tasks/main.yml
> +- include_tasks: tasks/java_tools_setup.yml
The home folder creation was moved into java_tools_setup.

2021-10-05 08:46 UTC, TomasHofman commented
@spyrkob I tried to make `java_tools_setup.yaml` self-contained, it should do everything now:
* download the archive,
* create home dir (/opt/oracle or /opt/ibm)
* unpack the archive to above dir,
* create simple simlink which is simpler / easier to remember than the full path

2021-10-05 08:49 UTC, TomasHofman commented
Also I removed the tool_install.yaml and moved the default links creation to main.yaml.

2021-10-05 12:33 UTC, spyrkob requested changes
When I tried running the change, there were some issues with importing certs into jdk6. I'll look into those a bit later

2021-10-05 12:33 UTC, spyrkob commented on roles/java/tasks/java_tools_setup.yml
> +        src: "{{ path_to_home }}"
that should be "{{ item.home }}/{{ item.name }}" path_to_home is stat structure

2021-10-18 11:41 UTC, spyrkob commented on roles/java_certs/tasks/main.yml
> +- name: "Provisioning self-signed certificate to JDKs"
Why is that only for default JDK? if there are any self-signed certificates, all JDKs would need them right?

2021-10-18 12:22 UTC, TomasHofman commented on roles/java_certs/tasks/main.yml
> +- name: "Provisioning self-signed certificate to JDKs"
Because you said that the keytool task doesn't work on JDK 6/7 :). Or at least that's how I understood it, maybe wrongly. I can test it out, I actually took it for granted.

ATM the JDK 6/7 is only used for EAP 6.4 jobs, and I currently don't think that I need any of those site certs for these jobs (at least not when I have the RH root cert imported). I didn't go all the way yet though, so maybe that will prove wrong.

2021-10-18 12:28 UTC, TomasHofman commented on roles/java_certs/tasks/main.yml
> +    $JDK_HOME/bin/keytool -list -noprompt -keystore $KEYSTORE -storepass $PASSWORD -alias $ALIAS \
IMO the return code of the expression `cmd1 || cmd2` is 0 if either of the commands returned 0.

2021-10-18 12:45 UTC, spyrkob commented on roles/java_certs/tasks/main.yml
> +    $JDK_HOME/bin/keytool -list -noprompt -keystore $KEYSTORE -storepass $PASSWORD -alias $ALIAS \
ah OK right I miss-read it

2021-10-18 12:46 UTC, spyrkob commented on roles/java_certs/tasks/main.yml
> +- name: "Provisioning self-signed certificate to JDKs"
If the build is going to use the cache it will need to import Olympus certificate

2021-12-17 08:25 UTC, closed without merging