SET-139 Automate CCI VMs setup with Ansible.
jboss-set/zeus pull request #115
Opened 2021-11-19 12:46 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/SET-139

2021-11-19 12:48 UTC, RanabirChakraborty commented
Follow the old conversation - https://github.com/jboss-set/zeus/pull/93

2021-11-22 12:52 UTC, spyrkob requested changes
Looking good. 

A couple notes for after this is merged: 
 * we'll need to pick parts of sshd role in as well to enable password login,
 * we should remove `jenkins` from sudoers - make sure it doesn't mess with Jenkins,
 * need to change JAVA_HOME and MAVEN_HOME in Jenkins before applying it

2021-11-22 12:52 UTC, spyrkob commented on automate_vm.yml
> +    - include_role:
Can this be added to roles rather than in pre_tasks?

2021-11-22 12:52 UTC, spyrkob commented on automate_vm.yml
> +    - vars/cci.yml
could you rename the vars in cci.yml to have `cci_worker_` prefix?

2021-11-22 12:52 UTC, spyrkob commented on automate_vm.yml
> +        password: "{{ credential_password }}"
Please rename the variables to `cci_worker_rhel_subscription_username` and `cci_worker_rhel_subscription_password`

2021-11-22 12:52 UTC, spyrkob commented on roles/sudoers/tasks/main.yml
> +    user_home: "/home/{{ username }}"
AFAIU this is not used here at all - can this be removed?

2021-11-22 12:52 UTC, spyrkob commented on automate_vm.yml
> +    - vars/ssh.yml
The `ssh.yml` vars need to be copied over to cci.yml and changed so that it only provides `jenkins` user and it's `identity_file` parameter points to a file in `/home/jenkins/.ssh`

2021-11-22 12:52 UTC, spyrkob commented on automate_vm.yml
> +---
I think the file should be called something like `cci_worker.yml` - a bit more descriptive

2021-11-22 12:52 UTC, spyrkob commented on automate_vm.yml
> +        user_home: "/home/{{ username }}"
I think this should either be set in vars or in `cci_account/defaults/main.yml`.

2021-11-22 12:52 UTC, spyrkob commented on automate_vm.yml
> +
Can you make sure `zip` package is installed on the VM as well?

2021-11-22 14:20 UTC, RanabirChakraborty commented on automate_vm.yml
> +    - vars/cci.yml
I can probably change a few vars names to `cci_worker_` prefix. mainly those are related to `sudoers` and `cci_account`.

2021-11-22 16:08 UTC, RanabirChakraborty commented
@spyrkob can you review once :)

2021-11-22 16:35 UTC, spyrkob approved these changes
LGTM

I'll run one more test tomorrow and merge it. Thanks @RanabirChakraborty !

2021-11-23 09:20 UTC, merged