pgsql: Refactors roles to use vars/ instead of defaults/ for internal…
jboss-set/zeus pull request #151
Opened 2022-02-22 10:37 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/SET-460

2022-02-22 10:38 UTC, RanabirChakraborty commented
While running the role `pgsql` found out that [mjolnir-preprod_data.sql](https://github.com/jboss-set/zeus/blob/olympus/roles/pgsql/defaults/main.yml#L16) doesn't exist.

2022-02-24 14:06 UTC, rpelisse requested changes
@RanabirChakraborty I've experience some errors when I tried this PR, so I'm holding off until you had a chance to check it out.

2022-02-24 16:39 UTC, RanabirChakraborty commented
Thanks! @rpelisse Did the required changes, and it's working fine now. (locally tested it)

2022-03-09 15:37 UTC, rpelisse approved these changes

2022-03-09 16:07 UTC, merged