SET-481 divide the list of roles under the roles: to pre_tasks, tasks…
jboss-set/zeus pull request #167
Opened 2022-04-08 10:37 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/SET-481

2022-04-08 10:38 UTC, RanabirChakraborty commented
Don't merge. Need to add other playbooks too.

2022-04-12 10:12 UTC, rpelisse commented
@RanabirChakraborty LGTM for CCI ! Please add the rh subs check to zeus.yml!

2022-04-12 10:12 UTC, rpelisse commented
@spyrkob can you review the CCI changes?

2022-04-12 12:22 UTC, rpelisse requested changes

2022-04-12 12:22 UTC, rpelisse commented on zeus.yml
> +    - ansible.builtin.include_role:
@RanabirChakraborty I would move "stage 1" to pre_tasks.

2022-04-12 12:22 UTC, rpelisse commented on zeus.yml
> +        - payload_status
As discussed, old_releases + the one below needs to be moved to a separate **playbook** (let's call jenkins.yml). Then at the end of this file, we can import the second playbook.

2022-04-13 14:07 UTC, spyrkob commented on cci_worker.yml
> +  post_tasks:
why are those  post_task not just included with tasks?

2022-04-13 16:36 UTC, RanabirChakraborty commented on cci_worker.yml
> +  post_tasks:
yes, it can be. But wanted to separate the tasks. `tasks` roles are doing the required setup and `post_tasks` are downloading the required things.

2022-04-14 10:41 UTC, spyrkob commented on cci_worker.yml
> +  post_tasks:
Personally I'd keep them together. I don't see what it's bringing and I think it's gonna cause confusion down the road. Otherwise looks good

2022-04-18 07:33 UTC, RanabirChakraborty commented on cci_worker.yml
> +  post_tasks:
Thanks! did the required changes.

2022-04-19 09:47 UTC, spyrkob approved these changes

2022-04-22 10:47 UTC, rpelisse approved these changes

2022-04-22 12:37 UTC, rpelisse requested changes
@RanabirChakraborty this PR introduce a dependency to community.general collection, which I'm not against, but we need to express it by adding an appropriate requirements.yml specifying this dependency and which version is requested.

2022-04-25 07:11 UTC, RanabirChakraborty commented
@rpelisse did the changes.

2022-05-25 10:10 UTC, rpelisse approved these changes

2022-05-25 10:20 UTC, rpelisse commented
Superseeded by [PR180](https://github.com/jboss-set/zeus/pull/180)

2022-05-25 10:21 UTC, closed without merging