SET-541 Configure Jenkins to use OIDC auth if configured
jboss-set/zeus pull request #207
Opened 2023-01-17 10:50 UTC by TomasHofman

https://issues.redhat.com/browse/SET-541

Changes in the `casc.yaml` to configure OIDC authorization plugin.

Two files are going to be created now, `casc-prod.yaml` and `casc-staging.yaml`. Even if both instances use the same SSO server, they at least need to have different location URL configured, so that SSO server redirects back to correct instance.

2023-01-17 10:51 UTC, TomasHofman commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.staging
Sanity check this please, the intention was that the `jenkins_sso.staging` variable would be available to the template under the name `instance`.

2023-01-17 10:54 UTC, TomasHofman commented
BTW do not merge yet, it needs one more change in Ares.

2023-01-17 11:08 UTC, spyrkob commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.prod
can you add `jenkins_sso.prod` and `jenkins_sso.stage` to the assert task?

2023-01-17 11:17 UTC, rpelisse requested changes

2023-01-17 11:17 UTC, rpelisse commented on roles/jenkins/tasks/main.yml
> +    dest: "{{ ares.home }}/hephaestus/casc-prod.yaml"
I think we should keep casc.yaml for prod and have casc-staging.yml for staging. (or casc-prod and casc-staging)

2023-01-17 11:17 UTC, rpelisse commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.staging
You don't need to duplicate the all task, just add a [loop:](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html) to the previous one and pass it the different destination

2023-01-17 11:17 UTC, rpelisse commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.staging
> Sanity check this please, the intention was that the jenkins_sso.staging variable would be available to the template under the name instance.

Regarding that I wonder if it would not simplier to maitain to have a "if stmt" in the template (if prod => bla, else => staging). It's not how Ansible would deal with that (there was to provides different values depending if the target is staging or prod, but in our case, I think it might be simplier to manage like that.

@spyrkob thoughts?

2023-01-17 11:28 UTC, spyrkob commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.staging
I'm not sure I'm getting what you're suggesting. Passing different variable to the template seems more readable then having a bunch of conditions in template, but maybe I'm missunderstanding

2023-01-17 11:35 UTC, rpelisse commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.staging
The if stag then instance = staging_vars else instance = prod_vars seems a bit wrong to me, while I cannot really put my finger on why exactly. That being said, we can go with that, it's not a blocker from my pov.

2023-01-17 14:33 UTC, TomasHofman commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.staging
I would leave it as it is, cause that's most readable to me :). I need to have different `vars` and also different `dest`. I can't wrap my head around how to make the `vars` directive part of a loop. Maybe it would need to be nested or something.

2023-01-17 14:37 UTC, TomasHofman commented on roles/jenkins/tasks/main.yml
> +    dest: "{{ ares.home }}/hephaestus/casc-prod.yaml"
Currently it is `casc-prod.yaml` and `casc-staging.yaml`, does that sound good?

2023-01-17 14:39 UTC, rpelisse commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.staging
Yeah, it might be the best option anyway. I'll deal with that when I test and merge, it'll be easier then!

2023-01-17 14:40 UTC, rpelisse commented on roles/jenkins/tasks/main.yml
> +    dest: "{{ ares.home }}/hephaestus/casc-prod.yaml"
With a loop, yes sounds good.

2023-01-17 14:43 UTC, TomasHofman commented on roles/jenkins/tasks/main.yml
> +    instance: jenkins_sso.prod
Done :+1:

2023-01-17 14:51 UTC, spyrkob approved these changes
LGTM

2023-01-17 15:19 UTC, TomasHofman commented
One last change to build `hephaestus.next` image from `hephaestus` dir.

2023-01-18 11:50 UTC, rpelisse commented
I've directly fixed the PR and added the commit, so we can close this.

2023-01-18 11:50 UTC, closed without merging