SET-718 Fix Zeus molecule issue
jboss-set/zeus pull request #241
Opened 2024-02-16 12:36 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/SET-718

2024-02-16 14:31 UTC, spyrkob submitted a review, later dismissed
Thanks, LGTM!

2024-02-16 14:33 UTC, spyrkob commented
sigh that's not the PR I meant to approve... @rpelisse could you review this before you merge it?

2024-02-16 17:26 UTC, rpelisse requested changes

2024-02-16 17:26 UTC, rpelisse commented on molecule/account/molecule.yml
> +    port_bindings:
Why do we need port-binding? I think we can remove those line, don't you think?

2024-02-19 07:52 UTC, RanabirChakraborty commented on molecule/account/molecule.yml
> +    port_bindings:
You are right we are not testing any systemd-based service, we can remove it.

2024-02-19 08:15 UTC, RanabirChakraborty commented on molecule/account/molecule.yml
> +    port_bindings:
@rpelisse modified it accordingly, Please review it.

2024-02-19 09:14 UTC, rpelisse approved these changes

2024-02-19 09:15 UTC, merged