SET-139 Automate CCI VMs setup with Ansible
jboss-set/zeus pull request #93
Opened 2021-08-24 13:03 UTC by rpelisse

2021-08-24 13:11 UTC, rpelisse reviewed
@RanabirChakraborty It's pretty good! Now, it's all about integrating into the roles already defined into Zeus to reduce code duplication.

2021-08-24 13:11 UTC, rpelisse commented on automate_vm/create_user.yml
> +    - name: Create and add user
This looks good, but we have role set up to create [account](https://github.com/jboss-set/zeus/blob/olympus/roles/account/tasks/main.yml) in Zeus. Can you look at using it instead?

2021-08-24 13:11 UTC, rpelisse commented on automate_vm/vmupdate.yml
> +    - name: Removing Openjdk-{{java_version}} tar file
For the Java and the MVn install, it looks good, but it duplicating code available in Zeus. Can you look at the role [java](https://github.com/jboss-set/zeus/blob/olympus/roles/java/tasks/main.yml) and try to use it with [include_role:](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_role_module.html)

2021-08-24 13:11 UTC, rpelisse commented on automate_vm/vmupdate.yml
> +        path: "/.bashrc"
That's a bit weird, /.bashrc should be /home/jboss/.bashrc, shouldn't it? (as it belongs to jboss user)

2021-08-24 13:11 UTC, rpelisse commented on automate_vm/vmupdate.yml
> +    - name: source the bashrc file
@RanabirChakraborty  This is still not going to work ;) Take a look at this [collection](https://docs.ansible.com/ansible/latest/collections/community/general/alternatives_module.html), if you want to implement something like that.

2021-08-24 13:19 UTC, RanabirChakraborty commented on automate_vm/create_user.yml
> +    - name: Create and add user
okay sure.

2021-08-24 13:20 UTC, RanabirChakraborty commented on automate_vm/vmupdate.yml
> +        path: "/.bashrc"
Okay, sure I'll do that.

2021-08-24 13:23 UTC, RanabirChakraborty commented on automate_vm/vmupdate.yml
> +    - name: source the bashrc file
It's working fine now. Earlier it has the issue because the user jboss didn't have sudo access.

2021-08-31 08:29 UTC, spyrkob commented
Should the sudo.conf.j2 be added to this PR?

The username/group properties should probably be in zeus-vars right?

2021-09-01 14:33 UTC, spyrkob commented
This should also set up yum repos, install git and import java certs

2021-09-01 14:36 UTC, rpelisse commented
@RanabirChakraborty we have a role for the java_certs stuff and also for Git that you might be able to reuse.

2021-09-01 14:55 UTC, spyrkob commented on automate_vm.yml
> +        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
Shouldn't that key be stored in zeus-vars?

2021-09-01 14:59 UTC, rpelisse commented
Not really, I think the idea is that if the user has deployed his key, Ansible will ensure it's added to the authorized key.
@RanabirChakraborty you may want to add a stat: task beforehand to check IF the file is there, before executing this action.
To address @spyrkob point, the path to the key should be override-able so that we can also deploy keys if needed:
`{{ override_path_to_ssh_key | default('~/.ssh/id_rsa.pub") }}`

2021-09-09 18:02 UTC, RanabirChakraborty commented
@rpelisse @spyrkob Thanks! it's working perfectly now.

2021-09-10 05:59 UTC, rpelisse commented on automate_vm.yml
> +          home: /home/{{ username }}
I would define a user_home variable:

```
- set_fact:
    user_home: "/home/{{ username }}"
```

I will come handy in the comment ;)

2021-09-10 05:59 UTC, rpelisse commented on automate_vm.yml
> +        path: ~/.ssh/authorized_keys
I would replace ~∕ by "{{ user_home }}"

2021-09-10 05:59 UTC, rpelisse commented on automate_vm.yml
> +        key: "{{ override_path_to_ssh_key | default('~/.ssh/id_rsa.pub') }}"
Same here ~/ => "{{ user_home }}"

2021-09-10 05:59 UTC, rpelisse commented on automate_vm.yml
> +
Just as good practice, because the playbook requires username to be defined to work, I would add an assert:

```
- assert:
     that:
        - username is defined
        - username | length > 0
      quiet: true
      fail_msg: "A smart and descriptive message :) "
```
```

2021-09-10 05:59 UTC, rpelisse commented on automate_vm.yml
> +    - name: Update yum
I would start by the yum update and put it just after the pre_tasks.

2021-09-10 07:46 UTC, rpelisse commented
On top of the few changes I've suggested, I think you should refactor the sudo part to be a small role (called sudoers). I would also organize the data around the user as a structure in the default/main.yml of the role, something like that:

```
user:
   sudoer: yes,
    name: "{{ username }}"
    gid: "{{ user_gid }}"
    uid: "{{ user_uid }}"
```

Then, in the role itself, you manipulate this structure and also fully test its content, at the beginning of the 

```
---
- assert:
      that:
        - user is defined
        - user.name is defined
        ...
```

2021-09-10 08:07 UTC, spyrkob commented on automate_vm.yml
> +        username: "{{ credential_username }}"
Do we have a service account for this? If not I'd rather subscribe directly to yum repos not the subscriptions

2021-09-14 12:25 UTC, RanabirChakraborty commented on automate_vm.yml
> +        username: "{{ credential_username }}"
@spyrkob subscribing directly to yum repos will take some manual work to put the link by ourselves. But if we register the RHEL system then it'll automatically do all the work and we don't need to worry or check again if we install any other RHEL repo.
I'm currently checking with the IT team to get a service account for the jboss-set team, we can use the credentials then.

2021-09-14 12:28 UTC, RanabirChakraborty commented on automate_vm.yml
> +
Did this inside the sudoers role.

2021-09-14 12:34 UTC, spyrkob commented on automate_vm.yml
> +        username: "{{ credential_username }}"
that seems to cover configuring the yum repo: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
or at worst it requires deploying a simple template.

I don't mind subscription, but keep in mind there will be multiple VMs booted from this image.

2021-09-14 13:20 UTC, rpelisse commented on automate_vm.yml
> +        username: "{{ credential_username }}"
@spyrkob you don't need to add a collection to use [yum_repository:](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html), it's part of the primitives of Ansible. I suspect the collection is just to use advanced features of Yum.

Booting multiple VM for the image should not be an issue if we do the subscription. For instance, I have ONE podman image with registrered and everytime I start a container based on it, I just need to run subscription-refresh and it works fine (mostly because, behind, it's employee one, so RHN does not care what we do :D ).

2021-10-12 11:12 UTC, spyrkob requested changes
I tried running this on a new VM and run into a lot of issues - details inline.

2021-10-12 11:12 UTC, spyrkob commented on automate_vm.yml
> +    - old_releases
`old_releases` requires `old_releases_url_override` variable. Probably need a file with common variables between CCI and Olympus

2021-10-12 11:12 UTC, spyrkob commented on automate_vm.yml
> +    - git
this role doesn't set a team key to access github - it's actuall in `ssh` role. We probably need to break it away

2021-11-19 12:47 UTC, RanabirChakraborty commented
Continuing here - https://github.com/jboss-set/zeus/pull/115

2021-11-22 13:48 UTC, closed without merging